CREATE TABLE movies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(300) NOT NULL,
    release_year INTEGER,

    CONSTRAINT ck_movies_title_not_blank
        CHECK (length(trim(title)) > 0),

    CONSTRAINT ck_movies_release_year
        CHECK (release_year > 0)
);

CREATE TABLE diary_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    movie_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PLANNED',
    rating SMALLINT,
    notes TEXT,

    CONSTRAINT fk_diary_entries_movie
        FOREIGN KEY (movie_id) REFERENCES movies (id),

    CONSTRAINT uq_diary_entries_movie
        UNIQUE (movie_id),

    CONSTRAINT ck_diary_entries_status
        CHECK (status IN ('PLANNED', 'WATCHED')),

    CONSTRAINT ck_diary_entries_rating
        CHECK (rating BETWEEN 1 AND 10),

    CONSTRAINT ck_diary_entries_rating_requires_watched
        CHECK (status = 'WATCHED' OR rating IS NULL)
);