spring.application.name=movie-journal

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

server.port=${PORT:8080}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.flyway.enabled=false

management.endpoint.health.show-components=always
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=20s